name: Tests

on:
  push:
    branches:
      - main
      - '*.x'

  pull_request:
  # schedule:
  #   - cron: '0 0 * * *'

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  tests:
    name: PHP tests (PHP ${{ matrix.php-version }})

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php-version: [8.2, 8.3, 8.4]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy .env
        run: cp .env.testing.example .env.testing

      - name: Generate key
        run: php artisan key:generate --env=testing

      - name: Install npm dependencies
        run: npm install

      - name: Run Build for Production
        run: npm run build

      - name: code style check
        run: ./vendor/bin/pint --test

      - name: Run tests
        run: php artisan test --parallel

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
